# rsync excludes file for arch-clone

# /
- /dev/*
- /lost+found/*
- /media/*
- /mnt/*
- /proc/*
- /run/*
- /sys/*
- /tmp/*

# etc
- /etc/NetworkManager/system-connections/*
- /etc/pacman.d/gnupg/*
- /etc/ssh/ssh_host_*
- /etc/fstab
- /etc/fstab.bak
- /etc/machine-id
- /etc/machine-id.bak
- /etc/mtab

# home
# ---- cache
- /home/*/.cache/*
# ---- config
- /home/*/.config/dconf
- /home/*/.config/fcitx
- /home/*/.config/ibus
- /home/*/.config/pulse
# ---- live
- /home/*/.live
# ---- local
+ /home/*/.local/
+ /home/*/.local/share/
+ /home/*/.local/share/xfce4/
+ /home/*/.local/share/xfce4/helpers/
+ /home/*/.local/share/xfce4/helpers/**
- /home/*/.local/share/**
- /home/*/.local/state/**
# ---- /
- /home/*/.gnupg
- /home/*/.pki
- /home/*/.ssh
- /home/*/.bash_history
- /home/*/.ICEauthority
- /home/*/.vboxclient-*.pid
- /home/*/.viminfo
- /home/*/.Xauthority
- /home/*/.xsession-errors
- /home/*/.xsession-errors.old

# root
+ /root/
+ /root/.vimrc
- /root/**

# usr
+ /usr/share/locale/
+ /usr/share/locale/en_US/
+ /usr/share/locale/en_US/**
+ /usr/share/locale/zh_CN/
+ /usr/share/locale/zh_CN/**
+ /usr/share/locale/locale.alias
- /usr/share/locale/**

# var
+ /var/
+ /var/lib/
+ /var/lib/pacman/
+ /var/lib/pacman/local/
+ /var/lib/pacman/local/**
+ /var/.updated
- /var/**
